# This file specifies the build dependencies for Github Action workflows and
# for local build environments. The workspace has four toplevel directories
# containing the user config, modules, zephy and ZMK.
#
# ZMK-Workspace
# ├── config
# ├── modules
# ├── zephyr
# └── zmk
#
# To create a local build environment, clone this repository and then run the
# following commands from its toplevel directory:
#
# $ west init -l config
# $ west update
# $ west zephyr-export
#
---
manifest:
  defaults:
    remote: urob
    # revision: v0.3 # Pin ZMK version

  remotes:
    - name: urob
      url-base: https://github.com/urob
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 6e2ef41e022d555b10f116e395832913f71717b3 # main (2026-08-18)
      import: app/west.yml

    # ZMK modules
    - name: zmk-adaptive-key
      path: modules/zmk/adaptive-key
      revision: e5b335a7b1076cb122582f5a892b118b02a3be34 # main (2026-08-18)
    - name: zmk-auto-layer
      path: modules/zmk/auto-layer
      revision: 62c201934711369d50a28df12e1d055d05cb6460 # main (2026-08-18)
    - name: zmk-helpers
      path: modules/zmk/helpers
      revision: bc114546392b4615ac90a99140eaf21dde31209d # main (2026-08-18)
    - name: zmk-leader-key
      path: modules/zmk/leader-key
      revision: e894d9afa5164b7fff641db4194fc3d4d6e84bbb # main (2026-08-18)
    - name: zmk-tri-state
      path: modules/zmk/tri-state
      revision: 269b13eb3f5491292b627ac3892589af32de3e17 # main (2026-08-18)
    - name: zmk-unicode
      path: modules/zmk/unicode
      revision: a1e3d3eed54dea800b5342a251eb3b83eee3b5ec # main (2026-08-18)

    # Only source necessary Zephyr modules. Remove this entire section to restore
    # the default (needed for less common hardware).
    - name: zephyr
      remote: zmkfirmware
      revision: 10ba6d0cb38bc3d258775d27982f707599320085 # v4.1.0+zmk-fixes
      clone-depth: 1
      import:
        name-allowlist:
          - cmsis
          - hal_nordic
          - hal_rpi_pico
          - hal_stm32
          - mbedtls
          - tinycrypt

  self:
    path: config
